[package]
name = "bevy-inspect-entity-hierarchy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_color = "0.17"
bevy_ecs = { version = "0.17", default-features = false, features = ["trace"] }
nu-ansi-term = "0.50.3"
